# Generated by Django 6.0 on 2026-01-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(default='Developer', help_text='Peran Anda dalam project ini', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='skills_used',
            field=models.TextField(default='exit', help_text='Skills yang digunakan dalam project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tools_used',
            field=models.TextField(default='VS Code, Git', help_text='Tools yang digunakan dalam project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Comma-separated tech stack', max_length=300),
        ),
    ]
