# Generated by Django 6.0 on 2026-02-10 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_project_category_project_end_date_project_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tools_used',
            field=models.TextField(blank=True, help_text='Tools yang digunakan dalam project'),
        ),
        migrations.CreateModel(
            name='ToolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(help_text='Nama tool (contoh: Excel, Word, Python)', max_length=100)),
                ('image', models.ImageField(help_text='Upload icon/logo tool', upload_to='tool_images/')),
                ('order', models.IntegerField(default=0, help_text='Urutan tampilan')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_images', to='myapp.project')),
            ],
            options={
                'verbose_name': 'Tool Image',
                'verbose_name_plural': 'Tool Images',
                'ordering': ['order', 'tool_name'],
            },
        ),
    ]
