# Generated by Django 6.0 on 2026-02-11 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_project_tools_used_toolimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(help_text='Foto profil untuk halaman About', upload_to='about/')),
                ('degree', models.CharField(default='Bachelor of Information Systems', max_length=200)),
                ('university', models.CharField(default='Universitas Komputer Indonesia', max_length=200)),
                ('year', models.CharField(default='2021 - Present', max_length=100)),
                ('gpa', models.CharField(default='3.62/4.00', max_length=20)),
                ('transcript', models.FileField(blank=True, help_text='Upload transcript PDF', null=True, upload_to='documents/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nama area of interest', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Urutan tampilan')),
                ('is_active', models.BooleanField(default=True, help_text='Tampilkan di halaman About')),
            ],
            options={
                'verbose_name': 'Area of Interest',
                'verbose_name_plural': 'Areas of Interest',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='toolimage',
            name='image',
        ),
        migrations.AddField(
            model_name='toolimage',
            name='tool_image',
            field=models.ImageField(default='default.png', help_text='Logo/icon tool', upload_to='tool_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, help_text='Kategori project', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Tanggal selesai project', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Tanggal mulai project', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools_used',
            field=models.TextField(help_text='Tools yang digunakan dalam project'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.project'),
        ),
        migrations.AlterField(
            model_name='toolimage',
            name='tool_name',
            field=models.CharField(help_text='Nama tool/teknologi', max_length=100),
        ),
    ]
