# Generated by Django 6.0 on 2026-02-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_aboutpage_interest_remove_toolimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama skill/tool', max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming Languages'), ('framework', 'Frameworks & Libraries'), ('database', 'Databases'), ('tool', 'Tools & Platforms'), ('ml', 'Machine Learning & AI'), ('visualization', 'Data Visualization'), ('other', 'Other')], default='other', help_text='Kategori skill', max_length=50)),
                ('image', models.ImageField(help_text='Logo/icon skill', upload_to='skills/')),
                ('proficiency', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], help_text='Tingkat kemahiran', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Urutan tampilan dalam kategori')),
                ('is_active', models.BooleanField(default=True, help_text='Tampilkan di halaman About')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
